### ISSUE TITLE
Access

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/datasets.illumina#2]
@eparejatobes I don't have push access in this repo. I need it to update the build and make a release (for MG7).

**Comment by laughedelic** [comment]
I published `0.0.0-5-g811df8d` meanwhile.

**Comment by eparejatobes** [comment]
Done. Next time assign me, please.

**Comment by laughedelic** [comment]
@eparejatobes I couldn't even assign or apply labels. That's why I mentioned you.

**Comment by eparejatobes** [comment]
fair enough :)
